# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: docker/compose

options:
    docker: true
    size: 2x

pipelines:
    cyc:
        - step:
              name: 'Build and Test'
              script:
                  - echo "Your build and test goes here..."
                  - docker-compose up
                  - docker-compose down
                  - docker --help
