# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
    default:
        - step:
              name: 'Build and Test'
              script:
                  - echo "Your build and test goes here..."
                  - docker compose up --force-recreate --build

