# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: docker/compose

options:
    docker: true
    size: 2x
    max-time: 25

pipelines:
    pull-requests:
        '**': #this runs as default for any branch not elsewhere defined
            - step:
                  size: 2x
                  name: 'Build and Test'
                  script:
                      - echo "Your build and test goes here..."
                      - docker-compose up --exit-code-from cypress
                  services:
                      - docker
    branches:
        master:
            - step:
                  size: 2x
                  name: 'Build and Test'
                  script:
                      - echo "Your build and test goes here..."
                      - docker-compose up --exit-code-from cypress
                  services:
                      - docker

    custom:
        publish-to-docker-hub:
            - step:
                  size: 2x
                  name: 'Build and Test and Upload to Dockerhub'
                  script:
                      - echo "Your build and test goes here..."
                      - docker-compose up --exit-code-from cypress
                      - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
                      - docker info
                      - docker build -t https://index.docker.io/v1/cycai/cnext:v0.2.1 .
                      - docker push https://index.docker.io/v1/cycai/cnext:v0.2.1
                  services:
                      - docker

definitions:
    services:
        docker:
            memory: 4096
