version: '3'

services:
    web:
        # image: ${IMAGE_NAME}:${IMAGE_TAG}
        build: .
        container_name: web
        working_dir: /app/cyc_next_app
        ports:
            - ${CLIENT_PORT}:3000
        command: npm start

    server:
        # image: ${IMAGE_NAME}:${IMAGE_TAG}
        build: .
        container_name: server
        working_dir: /app/cyc_next_app/server
        volumes:
            - ${SOURCE_PROJECT_DIR}:/app/cyc_next_app/server/cnext_sample_projects/Skywalker
        ports:
            - ${SERVER_PORT}:4000
        command: /bin/sh -c "./start.sh"
