version: '3'

services:
    server:
        build:
            context: ./cyc-next-app/server
            dockerfile: Dockerfile

        container_name: server
        ports:
            - 4000:4000

    web:
        build:
            context: ./cyc-next-app
            dockerfile: Dockerfile

        container_name: web
        depends_on:
            - server
        ports:
            - 3000:3000

    cypress:
        image: cypress
        build: ./cyc-next-app/tests/intergration
        container_name: cypress
        depends_on:
            - web
            - server
        environment:
            - CYPRESS_baseUrl=http://web:3000
        command: npx cypress run --record --key 5a02471d-2779-4256-bd4b-58ec1efa6929
        volumes:
            - ./cyc-next-app/tests/intergration/cypress:/app/cypress
            - ./cyc-next-app/tests/intergration/cypress.json:/app/cypress.json
