FROM python:3.9.7

RUN mkdir /app
WORKDIR /app

COPY . .

ENV PYTHONPATH=${PYTHONPATH}:${PWD}

RUN pip3 install poetry
RUN poetry config virtualenvs.create false
RUN poetry --version
RUN poetry install --no-dev
RUN poetry build
RUN poetry publish -u hoatv -p Hoa@761991
