# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
    ['cyc_next_app',
     'cyc_next_app.lib.@jupyter-widgets.schema',
     'cyc_next_app.server',
     'cyc_next_app.server.python',
     'cyc_next_app.server.python.cassist',
     'cyc_next_app.server.python.code_editor',
     'cyc_next_app.server.python.dataframe_manager',
     'cyc_next_app.server.python.experiment_manager',
     'cyc_next_app.server.python.file_explorer',
     'cyc_next_app.server.python.file_manager',
     'cyc_next_app.server.python.libs',
     'cyc_next_app.server.python.project_manager',
     'cyc_next_app.server.python.user_space',
     'cyc_next_app.server.python.user_space.ipython',
     'cyc_next_app.server.tests',
     'cyc_next_app.server.tests.test_servers']

package_data = \
    {'': ['*'],
     'cyc_next_app': ['lib/@jupyter-widgets/base/*',
                      'lib/@jupyter-widgets/base/css/*',
                      'lib/@jupyter-widgets/base/lib/*',
                      'lib/@jupyter-widgets/controls/*',
                      'lib/@jupyter-widgets/controls/css/*',
                      'lib/@jupyter-widgets/controls/lib/*',
                      'lib/@jupyter-widgets/controls/lib/phosphor/*',
                      'lib/@jupyter-widgets/html-manager/*',
                      'lib/@jupyter-widgets/html-manager/css/*',
                      'lib/@jupyter-widgets/html-manager/lib/*',
                      'lib/@jupyter-widgets/jupyterlab-manager/*',
                      'lib/@jupyter-widgets/jupyterlab-manager/lib/*',
                      'lib/@jupyter-widgets/jupyterlab-manager/schema/*',
                      'lib/@jupyter-widgets/output/*',
                      'lib/@jupyter-widgets/output/lib/*',
                      'lib/@jupyter-widgets/schema/v1/*',
                      'lib/@jupyter-widgets/schema/v2/*',
                      'lib/cassist/*',
                      'lib/codemirror/autocomplete-lsp/*',
                      'lib/codemirror/autocomplete-lsp/autocomplete/*',
                      'lib/codemirror/basic-setup/*',
                      'lib/codemirror/grammar/*',
                      'lib/components/*',
                      'lib/components/code-panel/*',
                      'lib/components/dataframe-manager/*',
                      'lib/components/file-manager/*',
                      'lib/components/libs/*',
                      'lib/components/richoutput-panel/*',
                      'lib/components/richoutput-panel/data-panel/*',
                      'lib/components/richoutput-panel/experiment-panel/*',
                      'lib/components/richoutput-panel/model-panel/*',
                      'lib/components/richoutput-panel/result-panel/*',
                      'lib/components/richoutput-panel/summary-panel/*',
                      'lib/components/sidebar/*',
                      'lib/components/tests/*',
                      'lib/interfaces/*',
                      'pages/*',
                      'public/*',
                      'public/icons/*',
                      'redux/*',
                      'redux/actions/*',
                      'redux/reducers/*',
                      'redux/store/*',
                      'styles/*',
                      'tests/intergration/Dockerfile',
                      'tests/intergration/Dockerfile',
                      'tests/intergration/Dockerfile',
                      'tests/intergration/Dockerfile',
                      'tests/intergration/cypress.json',
                      'tests/intergration/cypress.json',
                      'tests/intergration/cypress.json',
                      'tests/intergration/cypress.json',
                      'tests/intergration/cypress/fixtures/*',
                      'tests/intergration/cypress/integration/cyc/*',
                      'tests/intergration/cypress/integration/data/*',
                      'tests/intergration/cypress/plugins/*',
                      'tests/intergration/cypress/results/*',
                      'tests/intergration/cypress/support/*',
                      'tests/intergration/old-test.js',
                      'tests/intergration/old-test.js',
                      'tests/intergration/old-test.js',
                      'tests/intergration/old-test.js',
                      'tests/intergration/package.json',
                      'tests/intergration/package.json',
                      'tests/intergration/package.json',
                      'tests/intergration/package.json',
                      'tests/unit/*',
                      'tests/unit/pages/*',
                      'theme/*'],
     'cyc_next_app.server': ['build/*', 'ls/*', 'routes/*']}

install_requires = \
    ['PyYAML>=6.0,<7.0',
     'pysqlite3<0.5.0,>=0.4.7',
     'astroid>=2.9.0,<3.0.0',
     'attrs>=21.4.0,<22.0.0',
     'autopep8>=1.5.6,<2.0.0',
     'backcall>=0.2.0,<0.3.0',
     'bleach>=4.1.0,<5.0.0',
     'bottleneck>=1.3.2,<2.0.0',
     'branca>=0.4.2,<0.5.0',
     'certifi>=2021.10.8,<2022.0.0',
     'debugpy>=1.5.1,<2.0.0',
     'decorator>=5.1.1,<6.0.0',
     'defusedxml>=0.7.1,<0.8.0',
     'entrypoints>=0.3,<0.4',
     'flake8>=3.9.0,<4.0.0',
     'future>=0.18.2,<0.19.0',
     'geos>=0.2.3,<0.3.0',
     'importlib-metadata>=4.8.2,<5.0.0',
     'importlib_resources>=5.4.0,<6.0.0',
     'intel-openmp>=2022.0.3,<2023.0.0',
     'ipydatawidgets>=4.2.0,<5.0.0',
     'ipykernel>=6.4.1,<7.0.0',
     'ipyleaflet>=0.15.0,<0.16.0',
     'ipython>=7.31.1,<8.0.0',
     'ipython_genutils>=0.2.0,<0.3.0',
     'ipywidgets>=7.6.5,<8.0.0',
     'isort>=5.9.3,<6.0.0',
     'jedi>=0.17.2,<0.18.0',
     'jinja2>=3.0.3,<4.0.0',
     'jsonschema>=4.4.0,<5.0.0',
     'lazy-object-proxy>=1.6.0,<2.0.0',
     'markupsafe>=2.1.0,<3.0.0',
     'matplotlib-inline>=0.1.2,<0.2.0',
     'matplotlib>=3.5.1,<4.0.0',
     'mccabe>=0.6.1,<0.7.0',
     'mistune>=0.8.4,<0.9.0',
     'mkl-service>=2.4.0,<3.0.0',
     'mkl_fft>=1.3.1,<2.0.0',
     'mkl_random>=1.2.2,<2.0.0',
     'mlflow>=1.25.1,<2.0.0',
     'multipledispatch>=0.6.0,<0.7.0',
     'nbconvert>=5.6.1,<6.0.0',
     'nbformat>=5.2.0,<6.0.0',
     'nest-asyncio>=1.5.1,<2.0.0',
     'notebook>=5.7.11,<6.0.0',
     'numexpr>=2.8.1,<3.0.0',
     'numpy>=1.22.3,<2.0.0',
     'packaging>=21.3,<22.0',
     'pandas>=1.4.2,<2.0.0',
     'pandocfilters>=1.5.0,<2.0.0',
     'parso>=0.7.0,<0.8.0',
     'pexpect>=4.8.0,<5.0.0',
     'pickleshare>=0.7.5,<0.8.0',
     'pip>=21.2.4,<22.0.0',
     'platformdirs>=2.4.0,<3.0.0',
     'plotly>=5.3.1,<6.0.0',
     'pluggy>=1.0.0,<2.0.0',
     'prometheus_client>=0.13.1,<0.14.0',
     'prompt-toolkit>=3.0.20,<4.0.0',
     'ptyprocess>=0.7.0,<0.8.0',
     'pyOpenSSL>=22.0.0,<23.0.0',
     'pyblas>=0.0.10,<0.0.11',
     'pycodestyle>=2.6.0,<3.0.0',
     'pydocstyle>=6.1.1,<7.0.0',
     'pyflakes>=2.2.0,<3.0.0',
     'pygments>=2.11.2,<3.0.0',
     'pylint>=2.12.2,<3.0.0',
     'pyparsing>=3.0.4,<4.0.0',
     'pyrsistent>=0.18.1,<0.19.0',
     'pysodium>=0.7.11,<0.8.0',
     'pysqlite3>=0.4.7,<0.5.0',
     'python-dateutil>=2.8.2,<3.0.0',
     'python-jsonrpc-server>=0.4.0,<0.5.0',
     'python-language-server>=0.36.2,<0.37.0',
     'python-xz>=0.4.0,<0.5.0',
     'pythreejs>=2.3.0,<3.0.0',
     'pytz>=2021.3,<2022.0',
     'pyyaml>=6.0,<7.0',
     'pyzmq>=22.3.0,<23.0.0',
     'rope>=0.22.0,<0.23.0',
     'send2trash>=1.8.0,<2.0.0',
     'setuptools>=58.0.4,<59.0.0',
     'shapely>=1.8.0,<2.0.0',
     'simplejson>=3.17.6,<4.0.0',
     'six>=1.16.0,<2.0.0',
     'snowballstemmer>=2.2.0,<3.0.0',
     'tk>=0.1.0,<0.2.0',
     'toml>=0.10.2,<0.11.0',
     'tornado>=6.1,<7.0',
     'traitlets>=5.1.1,<6.0.0',
     'traittypes>=0.2.1,<0.3.0',
     'typing-extensions>=3.10.0.2,<4.0.0.0',
     'typing_extensions>=3.10.0.2,<4.0.0.0',
     'tzdata>=2021e,<2022',
     'ujson>=4.2.0,<5.0.0',
     'wcwidth>=0.2.5,<0.3.0',
     'webencodings>=0.5.1,<0.6.0',
     'wheel>=0.37.1,<0.38.0',
     'widgetsnbextension>=3.5.2,<4.0.0',
     'wrapt>=1.13.3,<2.0.0',
     'xyzservices>=2022.3.0,<2023.0.0',
     'yapf>=0.31.0,<0.32.0',
     'zmq>=0.0.0,<0.0.1', ]

entry_points = \
    {'console_scripts': ['cnext-init = cyc_next_app.__main__:main',
                         'cnext-run = cyc_next_app.__main__:start']}

setup_kwargs = {
    'name': 'cyc-next-app',
    'version': '25.0.0',
    'description': 'improve your work',
    'long_description': None,
    'author': 'cyc ai company',
    'author_email': None,
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.9.7,<4.0.0',
}


setup(**setup_kwargs)
