p2n_comm:
    host: tcp://127.0.0.1
    n2p_port: 5000
    p2n_port: 5001

path_to_cycdataframe_lib: ''

projects:
    open_projects:
        - id: '1'
          name: 'Skywalker'
          path: '/Users/bachbui/works/cycai/cnext-working-dir/Skywalker'
    active_project: '1'

# p2n_comm:
#     host: tcp://127.0.0.1
#     n2p_port: 5000
#     p2n_port: 5001

# path_to_cycdataframe_lib: 'D:/DEV/CycAI/'

# projects:
#     open_projects:
#         - id: '1'
#           name: 'Skywalker'
#           path: 'D:/DEV/CycAI/cnext_sample_projects/Skywalker'
#     active_project: '1'
