node_py_zmq:
  host: tcp://127.0.0.1
  n2p_port: 5000
  p2n_port: 5001
  p2n_notif_port: 5002

path_to_cycdataframe_lib: '../../../'

projects:
  open_projects:
    -
      id: '1'
      name: Skywalker
      path: /Users/bachbui/works/cycai/cnext-working-dir/Skywalker  
  active_project: '1'