p2n_comm:
    host: tcp://127.0.0.1
    n2p_port: 5000
    p2n_port: 5001

# non_code_executor_comm:
#   host: tcp://127.0.0.1
#   n2p_port: 5002
#   p2n_port: 5003

path_to_cycdataframe_lib: "../../../"
# point to app on language server
path_lsp: ""

projects:
    open_projects:
        - id: "1"
          name: Skywalker
          path: /Users/bachbui/works/cycai/cnext-working-dir/Skywalker
    active_project: "1"
