p2n_comm:
    host: tcp://127.0.0.1
    n2p_port: 5000
    p2n_port: 5001

path_to_cycdataframe_lib: 'cycdataframe'

projects:
    open_projects:
        - id: '1'
          name: 'Skywalker'
          path: 'cnext_sample_projects/Skywalker'
    active_project: '1'
    
# p2n_comm:
#     host: tcp://127.0.0.1
#     n2p_port: 5000
#     p2n_port: 5001

# path_to_cycdataframe_lib: 'G:/DEV/CycAI/cycdataframe'

# projects:
#     open_projects:
#         - id: '1'
#           name: 'Skywalker'
#           path: 'G:/DEV/CycAI/cnext_sample_projects/Skywalker'
#     active_project: '1'
