version: '3'

services:
  server:
    build:
      context: /server
      dockerfile: Dockerfile

    container_name: server
    ports:
      - 4000:4000

  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: web
    depends_on:
      - server
    ports:
      - 3000:3000

  cypress:
    image: cypress
    build: ./e2e
    container_name: cypress
    depends_on:
      - web
      - server
    environment:
      - CYPRESS_baseUrl=http://web:3000
    command: npx cypress run
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.json:/app/cypress.json

    # image: 'cypress/included:9.5.2'

    # container_name: cypress

    # ports:
    #   - 5000:5000
    # networks:
    #   - my-network

    # working_dir: /cypress
    # volumes:
    #   - ./:/cypress
# networks:
#   my-network:
