version: '3'

services:
    server:
        build:
            context: /server
            dockerfile: Dockerfile

        container_name: server
        ports:
            - 4000:4000
        environment:
            - CLIENT_URL = http://web:3000

    web:
        build:
            context: .
            dockerfile: Dockerfile

        container_name: web
        depends_on:
            - server
        ports:
            - 3000:3000
        environment:
            - CODE_SERVER_SOCKET_ENDPOINT = http://server:4000


    cypress:
        image: cypress
        build: ./tests
        container_name: cypress
        depends_on:
            - web
            - server
        environment:
            - CYPRESS_baseUrl=http://web:3000
        command: npx cypress run
        volumes:
            - ./tests/cypress:/app/cypress
            - ./tests/cypress.json:/app/cypress.json

        # image: 'cypress/included:9.5.2'

        # container_name: cypress
        # depends_on:
        #   - web
        #   - server

        # environment:
        #   - CYPRESS_baseUrl=http://web:3000

        # working_dir: /cypress
        # volumes:
        #   - ./:/cypress
