version: '3'

services:
  server:
    build:
      context: /server
      dockerfile: Dockerfile

    container_name: server
    networks:
      - my-network

  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: web
    networks:
      - my-network
    ports:
      - '3000:80'
    depends_on:
      - server

  cypress:
    image: 'cypress/included:9.5.2'
    container_name: cypress
    networks:
      - my-network
    depends_on:
      - web
      - server
    environment:
      - CYPRESS_baseUrl=http://web:80
      - CYPRESS_VIDEO=false
    working_dir: /cypress
    volumes:
      - ./:/cypress
networks:
  my-network:
