name: Test

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:

  # prebuild:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #         cache: 'npm'
  #         cache-dependency-path: |
  #           cnext_app/package-lock.json
  #           cnext_server/server/package-lock.json

  #     - name: Install dependencies
  #       working-directory: ./cnext_app
  #       run: npm ci

  #     - name: Install dependencies
  #       working-directory: ./cnext_server/server
  #       run: npm ci

  #     - name: Install poetry
  #       run: pipx install poetry

  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.9'
  #         cache: 'poetry'

  #     - name: Install dependencies
  #       working-directory: ./cnext_server/server
  #       run: |
  #         poetry env use 3.9
  #         poetry install

  build:
    runs-on: ubuntu-latest
    # needs: prebuild
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: |
            cnext_app/package-lock.json
            cnext_server/server/package-lock.json

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'

      - name: Install dependencies
        working-directory: ./cnext_app
        run: npm ci

      - name: Install dependencies
        working-directory: ./cnext_server/server
        run: npm ci

      - name: Cache Next.js
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/cnext_app/.next/cache
          key: ${{ runner.os }}-app-${{ hashFiles('cnext_app/**.[jt]s', 'cnext_app/**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-app-

      - name: Build IDE
        working-directory: ./cnext_app
        run: npm run build

      - name: Install dependencies
        working-directory: ./cnext_server/server
        run: |
          poetry env use 3.9
          poetry install

      - name: Copy output
        run: cp -rf ./cnext_app/out ./cnext_server/public

      # - name: Cypress run
      #   uses: cypress-io/github-action@v4
      #   env:
      #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      #   with:
      #     record: true
      #     working-directory: cnext_app/tests/intergration
      #     browser: chrome
      #     start: |
      #       npm run  --prefix ../../../cnext_server/server start
      #     spec: |
      #       cypress/**/*.spec.js

#   # pypi:
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #     - name: Checkout
#   #       uses: actions/checkout@v3

#   #     - name: Set up Python 3.9
#   #       uses: actions/setup-python@v4
#   #       with:
#   #         python-version: '3.9'

#   #     - name: Install Poetry
#   #       run: pip install poetry

#   #     - name: Build project for distribution
#   #       run: poetry build

#   #     - name: Publish to PyPI
#   #       env:
#   #         POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
#   #       run: poetry publish

#   test-install:
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-latest, macos-latest]
#         # python-version: ["3.9", "3.10"]
#         python-version: ["3.9"]
#     runs-on: ${{ matrix.os }}
#     name: ${{ matrix.os }} Python ${{ matrix.python-version }}
#     steps:
#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Install CNext
#         run: pip install cnext

#       - name: Init CNext
#         run: echo "n" | cnext-init

#       - name: Run CNext
#         run: |
#           cnext-run &
