name: Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

env:
  BASE_DEV_VERSION: 0.10.3

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Build Variables
        run: |
          if [[ "$GITHUB_REF" =~ ^refs/tags/v* ]]; then
            echo "Using TAG mode: $GITHUB_REF_NAME"
            echo "REL_VERSION=$GITHUB_REF_NAME" >> $GITHUB_ENV
            echo "REL_VERSION_STRICT=${GITHUB_REF_NAME#?}" >> $GITHUB_ENV
          else
            echo "Using BRANCH mode: v$BASE_DEV_VERSION-dev.$GITHUB_RUN_NUMBER"
            echo "REL_VERSION=v$BASE_DEV_VERSION-dev.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
            echo "REL_VERSION_STRICT=$BASE_DEV_VERSION-dev.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          fi

      - name: Set Version
        run: |
          curl -sSLf "$(curl -sSLf https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep linux_amd64 | grep -v .gz | cut -d\" -f 4)" -L -o dasel && chmod +x dasel
          mv ./dasel /usr/local/bin/dasel
          dasel put string -f pyproject.toml .tool.poetry.version "$REL_VERSION_STRICT"
          cat pyproject.toml

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: |
            cnext_app/package-lock.json
            cnext_server/server/package-lock.json

      - name: Install dependencies
        working-directory: ./cnext_app
        run: npm ci

      - name: Install dependencies
        working-directory: ./cnext_server/server
        run: npm ci

      - name: Cache Next.js
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/cnext_app/.next/cache
          key: ${{ runner.os }}-app-${{ hashFiles('cnext_app/**/*.[jt]s', 'cnext_app/**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-app-

      - name: Build IDE
        working-directory: ./cnext_app
        run: npm run build

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'

      - name: Install dependencies
        working-directory: ./cnext_server/server
        run: |
          poetry env use 3.9
          poetry install

      - name: Copy output
        run: cp -rf ./cnext_app/out ./cnext_server/public

      # - name: Cypress run
      #   uses: cypress-io/github-action@v4
      #   env:
      #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      #   with:
      #     record: true
      #     working-directory: cnext_app/tests/intergration
      #     browser: chrome
      #     start: |
      #       npm run  --prefix ../../../cnext_server/server start
      #     spec: |
      #       cypress/**/*.spec.js

      - name: Build project for distribution
        run: |
          poetry env use 3.9
          poetry build

      - uses: actions/upload-artifact@v3
        with:
          name: python-package
          path: dist

      - uses: google-github-actions/release-please-action@v3
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          token: ${{secrets.BOT_TOKEN}}
          release-type: python
          package-name: cnext

      # - name: "Create release"
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   uses: actions/github-script@v6
      #   with:
      #     github-token: "${{ secrets.BOT_TOKEN }}"
      #     script: |
      #       const { REL_VERSION } = process.env

      #       await github.rest.repos.createRelease({
      #         draft: false,
      #         generate_release_notes: true,
      #         name: REL_VERSION,
      #         owner: context.repo.owner,
      #         prerelease: false,
      #         repo: context.repo.repo,
      #         tag_name: REL_VERSION,
      #       });

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish

      - name: Notify Slack Releases Channel
        if: startsWith(github.ref, 'refs/tags/v')
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "text": "CNext ${{ env.REL_VERSION }} has been released."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  docker:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download Dasel
        run: |
          curl -sSLf "$(curl -sSLf https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep linux_amd64 | grep -v .gz | cut -d\" -f 4)" -L -o dasel && chmod +x dasel
          mv ./dasel /usr/local/bin/dasel

      - name: Get version
        id: version
        run: echo "::set-output name=version::$(dasel select -f pyproject.toml .tool.poetry.version)"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: |
            CNEXT_VERSION=${{ steps.version.outputs.version }}
          tags: |
            cycai/cnext:latest
            cycai/cnext:v${{ steps.version.outputs.version }}

  # test-install:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest]
  #       # os: [ubuntu-latest, windows-latest, macos-latest]
  #       # python-version: ["3.9", "3.10"]
  #       python-version: ["3.9"]
  #   runs-on: ${{ matrix.os }}
  #   needs: build
  #   name: ${{ matrix.os }} Python ${{ matrix.python-version }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Download Dasel
  #       if: matrix.os == 'ubuntu-latest'
  #       run: |
  #         curl -sSLf "$(curl -sSLf https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep linux_amd64 | grep -v .gz | cut -d\" -f 4)" -L -o dasel && chmod +x dasel
  #         mv ./dasel /usr/local/bin/dasel

  #     - name: Download Dasel
  #       if: matrix.os == 'macos-latest'
  #       run: |
  #         curl -sSLf "$(curl -sSLf https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep -v .gz | grep darwin_amd64 | cut -d\" -f 4)" -L -o dasel && chmod +x dasel
  #         mv ./dasel /usr/local/bin/dasel

  #     - name: Download Dasel
  #       if: matrix.os == 'windows-latest'
  #       run: |
  #         scoop bucket add extras
  #         scoop install dasel

  #     - name: Get version
  #       id: version
  #       run: echo "::set-output name=version::$(dasel select -f pyproject.toml .tool.poetry.version)"

  #     - name: Set up Python ${{ matrix.python-version }}
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #         cache: 'pip'

  #     - name: Install CNext
  #       run: pip install cnext-test1==${{ steps.version.outputs.version }}

  #     - name: Init CNext
  #       run: echo "n" | cnext-init

  #     - name: Run CNext
  #       run: |
  #         cnext-run &
