name: Test

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'

      - name: Build IDE
        working-directory: ./cnext_app
        run: |
          npm install --force
          npm run build

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # - name: Cypress run
      #   uses: cypress-io/github-action@v4
      #   with:
      #     working-directory: cnext_app/tests/intergration
      #     start: |
      #       cd ../../ && npm run start
      #     spec: |
      #       cypress/**/*.spec.js
