name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:

  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: |
            cnext_app/package-lock.json
            cnext_server/server/package-lock.json

      - name: Install dependencies
        working-directory: ./cnext_app
        run: npm ci

      - name: Install dependencies
        working-directory: ./cnext_server/server
        run: npm ci

  build:
    runs-on: ubuntu-latest
    needs: prebuild
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: |
            cnext_app/package-lock.json
            cnext_server/server/package-lock.json

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'

      - name: Install dependencies
        working-directory: ./cnext_app
        run: npm ci

      - name: Install dependencies
        working-directory: ./cnext_server/server
        run: npm ci

      - name: Build IDE
        working-directory: ./cnext_app
        run: npm run build

      - name: Build Server
        working-directory: ./cnext_server/server
        run: |
          chmod +x start.sh
          poetry install

  # cypress-run:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #         cache: 'npm'
  #         cache-dependency-path: '**/package-lock.json'

  #     # Install NPM dependencies, cache them correctly
  #     # and run all Cypress tests
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v4
  #       env:
  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  #       with:
  #         record: true
  #         working-directory: cnext_app/tests/intergration
  #         browser: chrome
  #         start: |
  #           npm run  --prefix ../.. start
  #           npm run  --prefix ../../server start
  #         spec: |
  #           cypress/**/*.spec.js
